version: '3.8'
services:
  esbuild-client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src:ro
    environment:
      - PORT=3000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
